### ISSUE TITLE
Run REORG before VACUUM to physically delete data

### ISSUE THREAD

**Issue by tdikland** [databrickslabs/discoverx#60]
In the documentation of the `delete_by_class` functionality it is noted that running vacuum is required to remove all traces of your deleted rows. Due to new features in Delta Lake this is no longer 100% correct.

Delta Lake now offers several mechanisms to soft-delete data including:
- Dropping columns with [column mapping](https://learn.microsoft.com/en-us/azure/databricks/delta/delta-column-mapping) enabled.
- Deleting rows with [deletion vectors](https://learn.microsoft.com/en-us/azure/databricks/delta/deletion-vectors) enabled.
- Any data modifications on Photon-enabled clusters when deletion vectors are enabled.

To remove this data physically from the table one has to first run the `REORG TABLE ... APPLY (PURGE)` command before running `VACUUM` (taking into account the retention period).

For now I suggest to update the README.

**Comment by edurdevic** [comment]
Fixed with #98 .
Thanks for reporting this @tdikland
