### ISSUE TITLE
Feature Request: Exclude views and non-delta tables

### ISSUE THREAD

**Issue by sachinwadhwa** [databrickslabs/discoverx#72]
It will be great to have a feature to exclude/include:

1) Managed Tables
2) Views
3) Non-Delta tables

**Comment by souravg-db** [comment]
Feature added in [v0.0.8](https://github.com/databrickslabs/discoverx/releases/tag/v0.0.8)
Views are excluded and data formats can be provided as follows:
```
(dx.from_tables(from_table_statement)
.with_data_source_formats(["DELTA","JSON"])
.scan())
```
